### ISSUE TITLE
Add server name to boot.cfg

### ISSUE THREAD

**Issue by TecCheck** [TheNexusAvenger/Nexus-LU-Launcher#1]
This is just a small thing, but you could set the property `SERVERNAME` in `boot.cfg` to the name of the selected server. That would display the server name in LU.

**Comment by TheNexusAvenger** [comment]
This change is pretty straightforward to do. It should be just:
1. Change the GUI to pass a `ServerEntry` instead of just the server address in it (https://github.com/TheNexusAvenger/Nexus-LU-Launcher/blob/95f2d164da8add58ffca7ed08541a3816476af42/NLUL.GUI/State/Client.cs#L345). When/if patch servers are implemented for DLU support, this will be required either way.
2. Add `bootConfig["SERVERNAME"] = serverEntry.ServerName` after the IP change: https://github.com/TheNexusAvenger/Nexus-LU-Launcher/blob/1fe5c31764105ea82c500cbd6646147a66546055/NLUL.Core/Client/ClientRunner.cs#L220

I'll probably do this at some point, but it won't be soon.

**Comment by TheNexusAvenger** [comment]
Ended up being soon as part of a bug fix for macOS 10.14 and older. This is now up in V.0.3.3.
